%% generated:2025-10-28T18:10:58Z
flowchart LR
subgraph repo
  CoAgent["CoAgent"]
  CoCache["CoCache"]
  CoCache["CoCache"]
  CoCivium["CoCivium"]
  CoCivium["CoCivium"]
end
subgraph service
  AdviceInbox["Advice Inbox"]
end
subgraph Ungrouped
  AdviceInbox["Advice Inbox"]
  CoAgent["CoAgent"]
  CoCache["CoCache"]
  CoCivium["CoCivium"]
end
AdviceInbox --> |"feeds"| CoCivium
AdviceInbox --> CoCivium
CoAgent --> CoCivium
CoCache --> |"emits"| AdviceInbox
CoCache --> AdviceInbox
CoCache --> |"indexes"| CoAgent
CoCache --> CoAgent
CoCivium --> |"indexes"| CoCache
