# Lychee config for CoCivium
exclude = [
  "^mailto:",
  "^tel:",
  "^#",
  "^https://github.com/.*/(pull|issues)/.*"
]
max_retries = 3
retry_wait_time = 2
user_agent = "CoCiviumLinkChecker/0.1 (+https://cocivium.org)"
accept = ["200", "204", "301", "302", "403", "429"]
schemes = ["http", "https", "mailto"]
exclude_path = ["legacy/", "staging/", "insights/", "scroll/"]
