---
extends: default
rules:
  document-start: disable
  new-lines:
    type: unix        # require LF (matches GitHub runners and .gitattributes)
  line-length: disable
  empty-lines:
    max: 1
    level: error
  braces: disable
  colons: disable
