extends: default
ignore: |
  admin/setup/dist/**
  .github/ISSUE_TEMPLATE/_legacy/**
rules:
  indentation: disable
  empty-lines:
    max: 1
  line-length:
    max: 120
    level: warning
    allow-non-breakable-words: true
    allow-non-breakable-inline-mappings: true
  document-start: disable
  truthy: disable
