---
extends: default
ignore: |
  .github/labels.yml

rules:
  document-start: disable
  new-lines:
    type: unix
  line-length: disable
  empty-lines:
    max: 1
    level: error
  braces: disable
  colons: disable
