---
extends: default
rules:
  document-start: disable
  new-lines:
    type: any           # accept CRLF locally and LF on CI
  line-length: disable
  empty-lines:
    max: 1
    level: error
  braces: disable
  colons: disable
