param(
    [Parameter(Mandatory=$true)][string] $IndexJsonPath,
    [Parameter(Mandatory=$true)][string] $RecipeJsonPath,
    [Parameter(Mandatory=$true)][string] $OutputMarkdownPath
)
$ErrorActionPreference='Stop'
Set-StrictMode -Version Latest

if (-not (Test-Path $IndexJsonPath))  { throw "Missing index: $IndexJsonPath" }
if (-not (Test-Path $RecipeJsonPath)) { throw "Missing recipe: $RecipeJsonPath" }

$chunks = Get-Content -LiteralPath $IndexJsonPath -Raw -Encoding UTF8 | ConvertFrom-Json
$recipe = Get-Content -LiteralPath $RecipeJsonPath -Raw -Encoding UTF8 | ConvertFrom-Json

$persona   = $recipe.persona
$tier      = $recipe.tier
$spikiness = $recipe.spikiness
$max       = [int]$recipe.max_chunks

$filtered = $chunks | Where-Object {
    $hasPersona   = (-not $_.personas) -or ($_.personas.Count -eq 0) -or ($_.personas -contains $persona)
    $hasTier      = (-not $_.tier) -or ($_.tier -eq $tier)
    $hasSpikiness = (-not $_.spikiness) -or ($_.spikiness -eq $spikiness)
    $hasPersona -and $hasTier -and $hasSpikiness
}

if (-not $filtered) { throw "No chunks matched recipe persona=$persona tier=$tier spikiness=$spikiness" }

# v0 ordering: recipe can optionally specify explicit ids
$ordered = @()
if ($recipe.ids -and $recipe.ids.Count -gt 0) {
    foreach ($id in $recipe.ids) {
        $hit = $filtered | Where-Object { $_.id -eq $id } | Select-Object -First 1
        if ($hit) { $ordered += $hit }
    }
} else {
    $ordered = $filtered
}

$ordered = $ordered | Select-Object -First $max

$sb = New-Object System.Text.StringBuilder
$null = $sb.AppendLine("# CC View: $($recipe.name)")
$null = $sb.AppendLine()
$null = $sb.AppendLine("> Persona: $persona | Tier: $tier | Spikiness: $spikiness")
$null = $sb.AppendLine("> Generated by New-CCWeave.ps1")
$null = $sb.AppendLine()

foreach ($c in $ordered) {
    $null = $sb.AppendLine("---")
    $null = $sb.AppendLine()
    $null = $sb.AppendLine($c.text)
    $null = $sb.AppendLine()
    $null = $sb.AppendLine("<!-- id: $($c.id) -->")
    $null = $sb.AppendLine()
}

$sb.ToString() | Set-Content -LiteralPath $OutputMarkdownPath -Encoding UTF8
