name: AI-Receipt
description: Tiny, auditable AI-Receipt
labels: ["ai-receipt"]
body:
  - type: input
    id: title
    attributes:
      label: One-line title
      placeholder: "Bus board fix → urgent clinic ride"
    validations:
      required: true
  - type: textarea
    id: context
    attributes: { label: Context (1–2 lines) }
  - type: textarea
    id: prompt
    attributes: { label: Prompt to AI (short) }
  - type: textarea
    id: steps
    attributes: { label: Steps (bullets) }
  - type: textarea
    id: artifacts
    attributes: { label: Artifacts (paths / links) }
  - type: input
    id: one_improvement
    attributes: { label: One improvement }
  - type: textarea
    id: trust
    attributes: { label: Trust notes (PII, vetting, etc.) }
