---
---
name: Chore
description: Maintenance or refactor task
labels: ["type/chore"]
body:
  - type: textarea
    id: description
    attributes:
      label: Description
      description: What to change and why
      todo: Short, actionable
    validations:
      required: true

