blank_issues_enabled: false
contact_links:
  - name: Idea / Suggestion (fast)
    url: https://github.com/rickballard/CoCivium/issues/new?template=idea.yml
    about: Share a scoped idea to help CoCivium evolve.
  - name: Questions / Discussions
    url: https://github.com/rickballard/CoCivium/discussions
    about: Ask questions or propose larger topics.
