name: Markdown Lint
on:
  pull_request:
    paths:
      - '**/*.md'
  workflow_dispatch:
permissions:
  contents: read
jobs:
  mdl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v16
        with:
          globs: |
            **/*.md
