name: "Tension → PR comment (v2)"
description: "Render tension.json → Markdown; comment on PR even if file missing. Robust PR lookup."
inputs:
  json:
    description: "Path to tension.json"
    required: true
    default: "tension.json"
  md:
    description: "Path to write Markdown output"
    required: false
    default: "tension.md"
runs:
  using: "composite"
  steps:
    - name: Resolve PR number
      shell: bash
      env:
        GH_TOKEN: ${{ github.token }}
      run: |
        set -euo pipefail
        PR=""
        case "${{ github.event_name }}" in
          pull_request|pull_request_target)
            PR="${{ github.event.number }}"
            ;;
          *)
            # Fallback: find PR by head branch
            PR="$(gh pr list --head "$GITHUB_REF_NAME" --json number --jq ".[0].number" || true)"
            ;;
        esac
        echo "PR=$PR" >> "$GITHUB_ENV"

    - name: Ensure Markdown (create minimal if json missing)
      shell: bash
      run: |
        set -euo pipefail
        JSON="${{ inputs.json }}"
        MD="${{ inputs.md }}"
        if [ -f "$JSON" ]; then
          pwsh -NoProfile -File tools/Format-Tension.ps1 -InputPath "$JSON" -OutputPath "$MD"
        else
          printf "### PR Tension Summary\n\n" > "$MD"
          printf "pr | commenters | neg_hits | pos_hits | divergence\n" >> "$MD"
          printf "--- | --- | --- | --- | ---\n" >> "$MD"
          printf "%s | none | 0 | 0 | 0\n" "${PR:-unknown}" >> "$MD"
        fi
        echo "Rendered -> $MD"

    - name: Comment on PR
      if: always()
      env:
        GH_TOKEN: ${{ github.token }}
      shell: bash
      run: |
        set -euo pipefail
        if [ -z "${PR:-}" ]; then
          echo "No PR number resolved; skipping comment."
          exit 0
        fi
        gh pr comment "$PR" --body "$(cat "${{ inputs.md }}")"
