$ErrorActionPreference="Stop"
param([string]$RepoRoot,[string]$ManifestPath)
$man = Get-Content $ManifestPath -Raw | ConvertFrom-Json
$outPath = Join-Path (Split-Path $ManifestPath -Parent) $man.out
$buf = New-Object System.Collections.Generic.List[string]
$buf.Add("# " + $man.title)
if($man.decorate.toc){ $buf.Add("<!-- TOC will be generated by site pipeline; GitHub renders plain. -->") }
foreach($s in $man.sections){
  $buf.Add("") ; $buf.Add("# " + $s.title)
  $src = Join-Path (Split-Path $ManifestPath -Parent) $s.src
  if(Test-Path $src){ $buf.AddRange( (Get-Content $src -Raw) -split "`r?`n" ) }
  else { $buf.Add("> [missing] " + $s.src) }
}
$buf.Add("")
$content = ($buf -join "`r`n") + "`r`n"
Set-Content -Path $outPath -Encoding utf8NoBOM -Value $content

