param(
    [string]$RepoRoot = $(Join-Path $HOME 'Documents\GitHub\CoCivium')
)

$ErrorActionPreference = 'Stop'

Write-Host ">> Export-CoEthicsDashboardSnapshot: start" -ForegroundColor Cyan
Write-Host ("   - RepoRoot: {0}" -f $RepoRoot) -ForegroundColor Gray

$logRoot   = Join-Path $RepoRoot 'docs\CoEthicsGauge\CoEthicsLog'
$entriesDir= Join-Path $logRoot  'entries'
$dashPath  = Join-Path $RepoRoot 'docs\CoEthicsGauge\DASHBOARD_SNAPSHOT_v0.md'

if (-not (Test-Path $entriesDir)) {
    throw "Entries directory not found at $entriesDir"
}

$entries = @()

Get-ChildItem -Path $entriesDir -Recurse -Filter *.json | ForEach-Object {
    try {
        $raw = Get-Content $_.FullName -Raw
        $obj = $raw | ConvertFrom-Json

        $brandName = $obj.brand.display_name
        $brandId   = $obj.brand.id
        $region    = $obj.region.code
        $lensId    = $obj.lens.id
        $numeric   = $obj.overall_score.numeric
        $band      = $obj.overall_score.band
        $nods      = $obj.overall_score.nods_count
        $spanks    = $obj.overall_score.spanks_count

        $entries += [pscustomobject]@{
            BrandName = $brandName
            BrandId   = $brandId
            Region    = $region
            Lens      = $lensId
            Score     = $numeric
            Band      = $band
            Nods      = $nods
            Spanks    = $spanks
            Path      = $_.FullName.Substring($RepoRoot.Length+1)
        }
    }
    catch {
        Write-Warning ("   ! Failed to parse {0}: {1}" -f $_.FullName, $_.Exception.Message)
    }
}

if (-not $entries) {
    throw "No entries found under $entriesDir"
}

$entries = $entries | Sort-Object Region, Lens, BrandName

$lines = @()
$lines += "# CoEthicsGauge — Dashboard Snapshot v0"
$lines += ""
$lines += "Generated by `tools/CoEthicsGauge/Export-CoEthicsDashboardSnapshot.ps1`."
$lines += ""
$lines += ("_Last export: {0}_`n" -f (Get-Date).ToUniversalTime().ToString("yyyy-MM-dd HH:mm:ss 'UTC'"))
$lines += "| Brand | Region | Lens | Score | Band | Nods | Spanks | File |"
$lines += "|-------|--------|------|-------|------|------|--------|------|"

foreach ($e in $entries) {
    $lines += ("| {0} | {1} | {2} | {3} | {4} | {5} | {6} | `{7}` |" -f `
        $e.BrandName, $e.Region, $e.Lens, $e.Score, $e.Band, $e.Nods, $e.Spanks, $e.Path)
}

$linesText = [string]::Join([Environment]::NewLine, $lines)
$linesText | Set-Content -Path $dashPath -Encoding UTF8

Write-Host "   - Wrote dashboard snapshot -> $dashPath" -ForegroundColor Green
Write-Host ">> Export-CoEthicsDashboardSnapshot: done" -ForegroundColor Cyan
