name: ai-ops-export-pack
on:
  workflow_dispatch:
jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/github-script@v7
        id: build
        with:
          script: |
            const owner = context.repo.owner, repo = context.repo.repo;
            const issues = await github.paginate(github.rest.issues.listForRepo, {
              owner, repo, state: 'open', labels: 'ai-ops', per_page: 100
            });
            function red(s){ return (s||'').replace(/(sk-)[A-Za-z0-9]{20,}/g,'$1[REDACTED]'); }
            async function mitigations(num){
              const cs = await github.paginate(github.rest.issues.listComments,{owner,repo,issue_number:num,per_page:100});
              // include comments that look like mitigation notes
              const chosen = cs.filter(c => /mitigation|workaround|rollback/i.test(c.body||''));
              return chosen.map(c => `- ${new Date(c.created_at).toISOString()} — @${c.user.login}: ${red(c.body).slice(0,2000)}`).join("\n") || "_None_";
            }
            let out = `# AI Ops Export Pack (Sanitized)\nGenerated: ${new Date().toISOString()}\n\n`;
            for (const it of issues) {
              const sev = (it.labels.map(l=>l.name).find(n=>/^ai-sev:/.test(n))||'ai-sev:unknown').replace('ai-sev:','').toUpperCase();
              const existential = it.labels.some(l=>l.name==='ai-risk:existential') ? ' (🚨 existential)' : '';
              const age = Math.floor((Date.now()-new Date(it.created_at))/86400000);
              out += `## HIC Record — #${it.number} — ${it.title}\n`;
              out += `**Severity:** ${sev}${existential}  |  **Age:** ${age}d  |  **URL:** ${it.html_url}\n\n`;
              out += `### Summary\n${red(it.body)}\n\n`;
              out += `### Mitigations / Workarounds (from comments)\n${await mitigations(it.number)}\n\n`;
              out += `### Environment & Repro (attach repro capsule if present)\n_Add latest .reports/ai-repro-*.txt_\n\n---\n\n`;
            }
            core.setOutput('report', out);
      - name: Write report
        run: |
          mkdir -p .reports/export
          echo "${{ steps.build.outputs.report }}" > .reports/export/ai-ops-export-$(date -u +%Y%m%d-%H%M%SZ).md
      - uses: actions/upload-artifact@v4
        with:
          name: ai-ops-export
          path: .reports/export/*.md
