name: cc-megascroll
on:
  pull_request:
    paths:
      - "frameworks/CC-Scroll.parts/**"
      - "scripts/Build-CCMegascroll.ps1"
      - ".github/workflows/cc-megascroll.yml"
  workflow_dispatch: {}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Setup PowerShell
        uses: PowerShell/PowerShell@v1
        with:
          version: "7.4.x"
      - name: Build CC Megascroll
        shell: pwsh
        run: |
          Set-StrictMode -Version Latest; $ErrorActionPreference='Stop'
          if (-not (Test-Path 'scripts/Build-CCMegascroll.ps1')) {
            Write-Error "scripts/Build-CCMegascroll.ps1 missing"
          }
          ./scripts/Build-CCMegascroll.ps1
          if (-not (Test-Path 'frameworks/CC-Scroll.megascroll.md')) { throw "Megascroll md not produced" }
          if (-not (Test-Path 'site-human/assets/cc-scroll.html'))   { throw "Megascroll html not produced" }
      - name: Upload scroll artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cc-scroll
          path: |
            frameworks/CC-Scroll.megascroll.md
            site-human/assets/cc-scroll.html