name: codespell
on:
  push:
  pull_request:
permissions:
  contents: read
jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install codespell
        run: |
          python -m pip install --upgrade pip codespell
      - name: Run codespell
        run: |
          codespell \
            --ignore-words docs/lexicon/codespell-ignore.txt \
            --skip "legacy/**,staging/**,insights/**,scroll/**,notes/**,outreach/**,admin/**,scripts/**,*.png,*.jpg,*.svg,*.csv" \
            .
