---
name: codespell --config .codespellrc --ignore-words .codespell.words || true
on: [push, pull_request]
jobs:
  spell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: python -m pip install --upgrade pip codespell --config .codespellrc --ignore-words .codespell.words || true
      - run: codespell --ignore-words docs/lexicon/codespell-ignore.txt --skip "legacy/**,staging/_imported/**,*.png,*.jpg,*.svg" --config .codespellrc --ignore-words .codespell.words || true


