---
name: Deprecated Terms Sweep
on:
  push:
    paths: ['docs/**','site/**']
  pull_request:
    paths: ['docs/**','site/**']

jobs:
  sweep:
  continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check for deprecated terms
        shell: pwsh
        run: pwsh tools/deprecated-sweep.ps1


