name: diagrams

on:
  push:
    paths:
      - 'docs/diagrams/**'
      - 'docs/DIAGRAMS.md'
      - '.github/workflows/diagrams.yml'
  pull_request:
    paths:
      - 'docs/diagrams/**'
      - 'docs/DIAGRAMS.md'
      - '.github/workflows/diagrams.yml'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Build diagrams
        shell: pwsh
        run: |
          $ErrorActionPreference='Stop'
          pwsh -NoProfile -File "docs/diagrams/tools/build-diagrams.clean.ps1" -RepoRoot "$PWD"

      - name: Detect drift (DIAGRAMS.md, asset-graph.mmd)
        shell: pwsh
        run: |
          $ErrorActionPreference='Stop'
          git config core.autocrlf false
          git status --porcelain
          git diff --exit-code -- docs/DIAGRAMS.md docs/diagrams/render/asset-graph.mmd
