name: eol-check
on:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Fail PR if CRLF found in text files
        shell: bash
        run: |
          set -euo pipefail
          if git grep -nI $'\r' -- . ':!*.png' ':!*.jpg' ':!*.gif' ':!*.svg' ':!*.pdf' ; then
            echo "CRLF detected in the files above. Please convert to LF." >&2
            exit 1
          else
            echo "No CRLF detected."
          fi
