name: eol-check
on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review]
jobs:
  check:
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Collect changed files
        run: |
          base="${{ github.event.pull_request.base.sha }}"
          head="${{ github.sha }}"
          git diff --name-only "$base...$head" > changed.txt
          cat changed.txt
      - name: Fail if CRLF found in changed text files
        run: |
          set -euo pipefail
          mapfile -t files < <(grep -E '\.(md|txt|yml|yaml|json|csv|ps1|psm1|psd1|editorconfig)$' changed.txt || true)
          if [ ${#files[@]} -eq 0 ]; then
            echo "No relevant text files changed."
            exit 0
          fi
          bad=0
          for f in "${files[@]}"; do
            if [ -f "$f" ] && grep -n $'\r' "$f" >/dev/null; then
              echo "::error file=$f::CRLF detected (\r). Convert to LF."
              bad=1
            fi
          done
          exit $bad


