name: Guard
on: [push, pull_request]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate .gitattributes
        shell: pwsh
        run: ./tools/validate-gitattributes.ps1