name: Guard
on:
  push:
    paths: [.gitattributes, tools/validate-gitattributes.ps1]
  pull_request:
    paths: [.gitattributes, tools/validate-gitattributes.ps1]
jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Validate .gitattributes
        shell: pwsh
        run: ./tools/validate-gitattributes.ps1