name: label-docs-only
on:
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "docs/**"
      - "**/*.md"
      - "advice/**"
permissions:
  contents: read
  pull-requests: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
