name: Link Check
on:
  pull_request:
  schedule:
    - cron: "0 5 * * 1"  # Mondays 05:00 UTC
jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: lycheeverse/lychee-action@v1
        with:
          args: --config .lychee.toml --verbose .
