name: Markdown Lint
on:
  pull_request:
  push:
    branches: [main]
  workflow_dispatch:
jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v17
        with:
          config: .markdownlint-cli2.yaml
          globs: |
            **/*.md
            !admin/setup/dist/**
            !.github/ISSUE_TEMPLATE/_legacy/**
