name: markdownlint
on:
  push:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Run markdownlint
        run: |
          npm i -g markdownlint-cli@0.39.0
          markdownlint -c .markdownlint.yml -i .markdownlintignore "**/*.md"
