---
name: markdownlint || true
on: [push, pull_request]
jobs:
  lint:
    runs-on: ubuntu-latest

    continue-on-error: truesteps:
      - uses: actions/checkout@v4
      - run: npm install -g markdownlint-cli || true
      - run: markdownlint || true

