name: nasties-guard
on:
  push:
  pull_request:
jobs:
  guard:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: fail on merge markers in docs
        run: |
          if grep -R -nE "^(<<<<<<<|=======|>>>>>>>)" docs; then
            echo "::error file=docs::merge conflict markers found"
            exit 1
          fi
