name: phrasing-guard
on:
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.mdx'
      - '**/*.txt'
      - '**/*.yml'
      - '**/*.yaml'
  push:
    branches: [ main ]
    paths:
      - '**/*.md'
      - '**/*.mdx'
      - '**/*.txt'
      - '**/*.yml'
      - '**/*.yaml'
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Block 'consent not coercion'
        run: |
          set -e
          echo "Scanning for disallowed phrase…"
          if grep -RIni --include='*.md' --include='*.mdx' --include='*.txt' --include='*.yml' --include='*.yaml' \
                 --exclude-dir={.git,node_modules,dist,build,target,venv,.venv,vendor,coverage} \
                 'consent not coercion' .; then
            echo "::error::Use 'consent not coercion' instead."; exit 1
          fi