---
name: PR Labeler
on:
  push:
    paths-ignore:
      - 'legacy/**'
      - 'staging/_imported/**'
  pull_request:
    paths-ignore:
      - 'legacy/**'
      - 'staging/_imported/**'
  pull_request_target:
    types: [opened, synchronize, reopened]
permissions:
  contents: read
  pull-requests: write
jobs:
  label:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@v5
        with:
          configuration-path: .github/labeler.yml
