name: relocation-analyzer
on:
  pull_request:
    paths:
      - "**/*.md"
      - "tools/analyzers/relocation_analyzer.py"
      - ".relocation-policy.json"
jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.x" }
      - name: Run analyzer
        run: python tools/analyzers/relocation_analyzer.py
      - name: Upload report
        if: always()
        uses: actions/upload-artifact@v4
        with: { name: relocation-report, path: .reports/relocation_report.md, if-no-files-found: ignore }
      - name: PR summary
        if: always()
        run: |
          echo "## Relocation Analyzer" >> $GITHUB_STEP_SUMMARY
          [ -f .reports/relocation_report.md ] && cat .reports/relocation_report.md >> $GITHUB_STEP_SUMMARY || echo "_No report_"
