name: YAML Lint
on:
  workflow_dispatch:
  pull_request:
  push:
    branches: [main]
jobs:
  yamllint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          file_or_dir: .
          config_file: .yamllint.yml
          format: github
          strict: false
