name: YAML Lint
on:
  pull_request:
  push:
    branches: [ main ]
    paths:
      - '**/*.yml'
      - '**/*.yaml'
  workflow_dispatch:
jobs:
  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ibiqlik/action-yamllint@v3
        with:
          config_file: .yamllint.yml
          format: github
          strict: false
