name: YAML Lint
on:
  pull_request:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  yamllint:
    name: YAML Lint
    runs-on: ubuntu-latest
    steps:
        with:
          format: github
          strict: true
